name: Build and Release Dist

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Prepare release branch
        run: |
          VERSION=$(node -p "require('./package.json').version")
          # Guardamos el dist en un tmp
          mv dist ../dist

          # Cambiamos a la rama release
          git checkout --orphan release
          git reset --hard
          git clean -fdx

          # Copiamos dist al root
          mv ../dist/* .

          # Creamos un package.json mínimo
          cat <<EOT > package.json
          {
            "name": "yacoub-ui",
            "version": "$VERSION",
            "main": "index.es.js",
            "module": "index.es.js",
            "types": "index.d.ts"          
          }
          EOT

          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Release build $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
